name: lint
  
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout # Checks the repository content
        uses: actions/checkout@v2
      - name: setup python # Set up to use a specified Python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1 # Use Python version 3.9.1
      - name: execute linter # Run the linter/lint.py file
        run: |
          python linter/lint.py
