name: lint
  
on:
  push:
    branches: [ main ]
    paths: 'readme.md'
  pull_request:
    branches: [ main ]
    paths: 'readme.md'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1

      - name: Execute linter
        run: |
          python linter/lint.py
